# Generated by Django 5.1.6 on 2025-02-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seats_count',
            field=models.IntegerField(choices=[(4, '4 seats'), (6, '6 seats'), (8, '8 seats'), (10, '10 seats')]),
        ),
    ]
